Merge sort
juliusbrehme/AlgoVerse pull request #11
Opened 2023-12-12 09:58 UTC by Nesket

- Sorting part merged without any conflicts left behind. 
- Error when leaving the visualization before it ends solved too. 
- Readme file updated with sorting info.

2023-12-12 10:21 UTC, JarUml approved these changes
Everything seems to work

2023-12-12 10:57 UTC, JarUml requested changes
PLease add the remaining Sorting Algorithms

2023-12-13 10:55 UTC, Nesket commented
The remaining sorting algorithms were implemented.

2023-12-14 14:24 UTC, JarUml approved these changes

2023-12-14 14:24 UTC, merged